name: Update Himawari Wallpaper


on:

  schedule:

    # 每小时运行一次
    # GitHub Actions 不保证严格10分钟
    - cron: "0 * * * *"


  workflow_dispatch:



permissions:

  contents: write

  pages: write

  id-token: write



jobs:


  update:


    runs-on: ubuntu-latest



    steps:


      # ======================
      # 拉取代码
      # ======================

      - name: Checkout

        uses: actions/checkout@v4




      # ======================
      # Python环境
      # ======================

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"



      - name: Install dependencies

        run: |

          pip install -r requirements.txt




      # ======================
      # 生成图片
      # ======================

      - name: Generate images

        run: |

          python main.py




      # ======================
      # 检查生成结果
      # ======================

      - name: Check generated files

        run: |

          echo "Current UTC time:"

          date -u


          echo ""

          echo "Output directory:"

          ls -lah output





      # ======================
      # 保存历史图片
      # ======================

      - name: Save history images

        run: |

          mkdir -p public/history


          TIME=$(date -u +"%Y%m%d_%H%M%S")


          cp output/earth_desktop.webp \
          public/history/earth_desktop_${TIME}.webp


          cp output/earth_phone.webp \
          public/history/earth_phone_${TIME}.webp




      # ======================
      # 创建Pages目录
      # ======================

      - name: Prepare Pages

        run: |


          mkdir -p public



          cp output/earth_desktop.webp \
          public/earth_desktop.webp



          cp output/earth_phone.webp \
          public/earth_phone.webp



          date -u +"%Y-%m-%d %H:%M:%S UTC" \
          > public/update.txt



          echo "Generated update time:"

          cat public/update.txt




      # ======================
      # 配置Pages
      # ======================

      - name: Setup Pages

        uses: actions/configure-pages@v5




      # ======================
      # 上传Pages
      # ======================

      - name: Upload Pages artifact

        uses: actions/upload-pages-artifact@v3

        with:

          path: ./public





  deploy:


    needs: update


    runs-on: ubuntu-latest



    steps:



      - name: Deploy to GitHub Pages

        uses: actions/deploy-pages@v4
