name: Update Himawari Wallpaper


on:

  # 手动运行
  workflow_dispatch:


  # 每10分钟运行一次
  schedule:

    - cron: "*/10 * * * *"



# 权限
permissions:

  contents: read

  pages: write

  id-token: write



jobs:


  update:


    name: Generate images

    runs-on: ubuntu-latest



    steps:


      # 拉取代码

      - name: Checkout

        uses: actions/checkout@v4



      # Python环境

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"



      # 安装依赖

      - name: Install dependencies

        run: |

          pip install -r requirements.txt



      # 运行你的程序

      - name: Generate wallpaper

        run: |

          python main.py



      # 准备Pages文件

      - name: Prepare Pages

        run: |

          mkdir -p public


          cp output/earth_phone.webp public/

          cp output/earth_desktop.webp public/


          cat > public/index.html <<EOF

          <!DOCTYPE html>

          <html>

          <head>

          <meta charset="utf-8">

          <title>Himawari Earth</title>


          <style>

          body {

            background: black;

            color: white;

            text-align: center;

            font-family: Arial, sans-serif;

          }


          img {

            width: 90%;

            max-width: 600px;

          }


          a {

            color: white;

            font-size: 18px;

          }


          </style>


          </head>


          <body>


          <h2>
          Latest Himawari Earth
          </h2>


          <img src="earth_phone.webp">


          <p>

          <a href="earth_phone.webp">
          Phone Wallpaper
          </a>

          </p>


          <p>

          <a href="earth_desktop.webp">
          Desktop Wallpaper
          </a>

          </p>


          </body>


          </html>

          EOF



      # 上传Pages文件

      - name: Upload Pages artifact

        uses: actions/upload-pages-artifact@v3

        with:

          path: public





  deploy:


    name: Deploy Pages


    needs: update


    runs-on: ubuntu-latest



    environment:

      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}



    steps:


      - name: Deploy to GitHub Pages

        id: deployment

        uses: actions/deploy-pages@v4
